import os
import re

# List of all 100 Python practice questions
questions = [
    "Write a Python program to take two numbers as input and print their sum.",
    "Write a program to swap two numbers without using a third variable.",
    "Write a program to find the area of a circle from the given radius.",
    "Write a program to convert temperature from Celsius to Fahrenheit.",
    "Write a program to check whether a number is positive, negative, or zero.",
    "Write a program to check if a number is even or odd.",
    "Write a program to find the largest among three numbers.",
    "Write a program to check if a year is a leap year or not.",
    "Write a program to determine if a character is a vowel or consonant.",
    "Write a program to calculate a student's grade based on percentage marks.",
    "Print numbers from 1 to 100 using a loop.",
    "Print all even numbers between 1 and 50.",
    "Print the multiplication table of a given number.",
    "Find the factorial of a number using a loop.",
    "Calculate the sum of digits of a given number.",
    "Reverse a given integer number using a loop.",
    "Count the number of vowels in a given string.",
    "Generate a Fibonacci sequence up to n terms.",
    "Print all prime numbers between 1 and 100.",
    "Find the sum of all even numbers between 1 and n.",
    "Write a function to find the maximum of three numbers.",
    "Write a function to calculate the factorial of a number.",
    "Write a function to check whether a number is prime or not.",
    "Write a function to reverse a string.",
    "Write a function to count uppercase, lowercase, digits, and special characters in a string.",
    "Write a function that returns the sum of elements in a list.",
    "Write a function to check if a string is a palindrome.",
    "Write a function to find the greatest common divisor (GCD) of two numbers.",
    "Write a function to print a pattern like star triangle.",
    "Write a function to return the second largest number in a list.",
    "Write a program to find the largest and smallest element in a list.",
    "Write a program to remove duplicates from a list.",
    "Write a program to count occurrences of each element in a list.",
    "Write a program to find the sum and average of a list of numbers.",
    "Write a program to sort a list without using the sort method.",
    "Write a program to reverse a list.",
    "Write a program to merge two lists into one.",
    "Write a program to find common elements between two lists.",
    "Write a program to find the second largest element in a tuple.",
    "Write a program to convert a tuple into a list and vice versa.",
    "Write a program to count the number of words in a string.",
    "Write a program to remove all spaces from a string.",
    "Write a program to check if two strings are anagrams.",
    "Write a program to find the frequency of each character in a string.",
    "Write a program to replace all vowels in a string with asterisk.",
    "Write a program to capitalize the first letter of each word in a string.",
    "Write a program to remove punctuation from a string.",
    "Write a program to find the longest word in a string.",
    "Write a program to check if a substring exists in a given string.",
    "Write a program to reverse the order of words in a sentence.",
    "Create a dictionary of 5 students with their marks and print them.",
    "Write a program to find the student with the highest marks.",
    "Write a program to count the frequency of words in a sentence using a dictionary.",
    "Write a program to merge two dictionaries.",
    "Write a program to remove a key from a dictionary.",
    "Write a program to check whether a key exists in a dictionary.",
    "Write a program to sum all the values in a dictionary.",
    "Write a program to sort a dictionary by its values.",
    "Write a program to invert keys and values in a dictionary.",
    "Write a program to combine two lists into a dictionary.",
    "Write a program to find union, intersection, and difference of two sets.",
    "Write a program to remove duplicates from a list using a set.",
    "Write a program to check whether a set is a subset of another set.",
    "Write a program to find the symmetric difference between two sets.",
    "Write a program to find common elements between two sets.",
    "Write a Python program to read a text file and print its content.",
    "Write a program to count the number of lines, words, and characters in a file.",
    "Write a program to copy contents from one file to another.",
    "Write a program to find the most repeated word in a text file.",
    "Write a program to append user input to an existing file.",
    "Write a program to check if a number is an Armstrong number.",
    "Write a program to check if a number is a perfect number.",
    "Write a program to find the sum of the first n natural numbers.",
    "Write a program to find the LCM of two numbers.",
    "Write a program to find the power of a number without using ** operator.",
    "Write a program to convert a decimal number into binary, octal, and hexadecimal.",
    "Write a program to check whether a number is palindrome or not.",
    "Write a program to print all factors of a number.",
    "Write a program to find the smallest and largest digit in a number.",
    "Write a program to calculate compound interest.",
    "Write a program to find all unique elements from a list.",
    "Write a program to find all duplicate elements from a list.",
    "Write a program to find the intersection of three lists.",
    "Write a program to find the average of all even numbers in a list.",
    "Write a program to print elements that appear exactly twice in a list.",
    "Write a program to count how many times each word appears in a paragraph.",
    "Write a program to remove all numbers from a string.",
    "Write a program to extract digits from a string.",
    "Write a program to find the longest substring without repeating characters.",
    "Write a program to generate a random password with letters, digits, and symbols.",
    "Print a triangle pattern of numbers.",
    "Print a pyramid pattern of stars.",
    "Print Floyd’s triangle.",
    "Print a square number pattern.",
    "Print a diamond pattern using stars.",
    "Print a hollow square pattern.",
    "Print Pascal’s triangle.",
    "Print an inverted half-pyramid pattern.",
    "Print a pattern of alphabets like ABCD format.",
    "Print all alphabets with ASCII values."
]

# Create a safe folder name for each question
for i, question in enumerate(questions, start=1):
    folder_name = f"Q{i:03d}_" + re.sub(r'[^A-Za-z0-9_]', '', question.replace(" ", "_"))
    os.makedirs(folder_name, exist_ok=True)

print("✅ All question folders created successfully!")
